### ISSUE TITLE
Grant on administrative function pg_start_backup

### ISSUE THREAD

**Issue by mnietz** [ansible-collections/community.postgresql#132]
##### SUMMARY

I'm not able to grant execute rights to pg_start_backup function to any role using postgresql_privs Module. Please find a sample playbook and the exception below.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.9.24
  config file = /home/foo/git/ansible/ansible.cfg
  configured module search path = [u'/home/foo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.18 (default, Mar  8 2021, 13:02:45) [GCC 9.3.0]
```

##### OS / ENVIRONMENT
Ubuntu 20.04 (Ansible Host). Debian 10 (Postgresq Host) with Postgresql 11

##### STEPS TO REPRODUCE
```
- name: Just a Test
  hosts: pg1
  gather_facts: false

  tasks:

    - name: Grant execute on pg_start_backup to foo
      postgresql_privs:
        port: 5432
        database: postgres
        schema: pg_catalog
        type: function
        objs: "pg_start_backup(text,boolean,boolean)"
        state: present
        privs: EXECUTE
        roles: foo
      become_user: postgres
```

```
postgres=# \df+ pg_catalog.pg_start_backup 
List of functions
-[ RECORD 1 ]-------+-----------------------------------------------------------------------
Schema              | pg_catalog
Name                | pg_start_backup
Result data type    | pg_lsn
Argument data types | label text, fast boolean DEFAULT false, exclusive boolean DEFAULT true
Type                | func
Volatility          | volatile
Parallel            | restricted
Owner               | postgres
Security            | invoker
Access privileges   | postgres=X/postgres
Language            | internal
Source code         | pg_start_backup
Description         | prepare for taking an online backup
```

##### EXPECTED RESULTS

Permission to execute pg_start_backup ist granted to foo.

##### ACTUAL RESULTS

```
he full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_postgresql_privs_payload_pijzh5e1/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py", line 692, in manipulate_privs
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_postgresql_privs_payload_pijzh5e1/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py", line 1052, in main
  File "/tmp/ansible_postgresql_privs_payload_pijzh5e1/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py", line 694, in manipulate_privs
__main__.Error: Illegal function signature: "boolean".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/ansible-tmp-1630050360.89-1744351-116965364760712/AnsiballZ_postgresql_privs.py", line 102, in <module>
    _ansiballz_main()
  File "/var/tmp/ansible-tmp-1630050360.89-1744351-116965364760712/AnsiballZ_postgresql_privs.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/tmp/ansible-tmp-1630050360.89-1744351-116965364760712/AnsiballZ_postgresql_privs.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.database.postgresql.postgresql_privs', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_postgresql_privs_payload_pijzh5e1/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py", line 1071, in <module>
  File "/tmp/ansible_postgresql_privs_payload_pijzh5e1/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py", line 1057, in main
AttributeError: 'Error' object has no attribute 'message'
fatal: [pg1]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.7"
    }, 
    "changed": false, 
    "module_stderr": "Shared connection to 192.168.120.136 closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_postgresql_privs_payload_pijzh5e1/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py\", line 692, in manipulate_privs\r\nValueError: not enough values to unpack (expected 2, got 1)\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_postgresql_privs_payload_pijzh5e1/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py\", line 1052, in main\r\n  File \"/tmp/ansible_postgresql_privs_payload_pijzh5e1/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py\", line 694, in manipulate_privs\r\n__main__.Error: Illegal function signature: \"boolean\".\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/var/tmp/ansible-tmp-1630050360.89-1744351-116965364760712/AnsiballZ_postgresql_privs.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/var/tmp/ansible-tmp-1630050360.89-1744351-116965364760712/AnsiballZ_postgresql_privs.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/var/tmp/ansible-tmp-1630050360.89-1744351-116965364760712/AnsiballZ_postgresql_privs.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.database.postgresql.postgresql_privs', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_postgresql_privs_payload_pijzh5e1/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py\", line 1071, in <module>\r\n  File \"/tmp/ansible_postgresql_privs_payload_pijzh5e1/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py\", line 1057, in main\r\nAttributeError: 'Error' object has no attribute 'message'\r\n", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

**Comment by Andersson007** [comment]
@mnietz hello, thanks for reporting the issue!

1. Could you please first try to change `pg_start_backup(text,boolean,boolean)` to `pg_start_backup(text:boolean:boolean)` and run again?

2. If it doesn't help, is there a chance you install and use the latest version of the `community.postgresql` collection (2.9 works with the collections as well) and run your playbook with it. Here's a [tutorial](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html)

The problem now is that the code in 2.9 is buggy and we can't see the actual error message.

3. If there's no chance to use the collection, could you please change the line 1057 in `postgresql_privs.py` file to `module.fail_json(msg=to_native(e))`, run again and provide the traceback?

Thank you!

**Comment by mnietz** [comment]
@Andersson007 : Thank you! Using colons instead of comma solved the issue

**Comment by Andersson007** [comment]
@mnietz you're welcome!

**Comment by Andersson007** [comment]
I see now that there are no examples. Thank you for raising the issue, I'll create an issue to add examples!

**Comment by Andersson007** [comment]
https://github.com/ansible-collections/community.postgresql/issues/133
