### ISSUE TITLE
ansible task crashes with sudo user switch to postgres

### ISSUE THREAD

**Issue by codeInTheShell** [ansible-collections/community.postgresql#386]
##### SUMMARY
When trying to create a new user (on a freshly installed instance, that has not been configured), the user switch doesn't happen, even though  the test user on the remote system is in the sudoers file with all privileges and nopasswd. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_user

##### ANSIBLE VERSION
```ansible [core 2.12.4]
  config file = None
  configured module search path = ['/home/test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/test/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
ansible-galaxy collection list community.general

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.6.0  
```

##### OS / ENVIRONMENT
Target: Alpine Linux 3.17
Source: Ubuntu 22.10

##### STEPS TO REPRODUCE

```
---
- hosts: alpine
  gather_facts: true
  remote_user: test
  become: true
  become_method: sudo
  become_user: postgres

  vars:
    ansible_python_interpreter: /usr/bin/python


  tasks:
    - name: "Installing PostgreSQL"
      apk:
        name: "postgresql"
        state: present
    
    - name: "Enabling PostgreSQL service"
      ansible.builtin.service:
        name: postgresql
        enabled: true
    
    - name: "Starting PostgreSQL service"
      ansible.builtin.service:
        name: postgresql
        state: started
    
    - name: "Create user with password"
      community.postgresql.postgresql_user:
        login_host: "localhost"
        login_user: "postgres"
#      login_password: ""
        name: "test"
        password: "test"
#      become: true
#      become_method: sudo
#      become_user: "postgres"
      vars:
        ansible_ssh_pipelining: true
        ansible_shell_allow_world_readable_temp: true
```
**/etc/sudoers**
```
root ALL=(ALL:ALL) ALL
test ALL=(ALL:ALL) NOPASSWD: ALL
@includedir /etc/sudoers.d
```
##### EXPECTED RESULTS

User added to the db.

##### ACTUAL RESULTS
```
TASK [Create user with password] ********************************************************************************************************************
task path: /home/test/Git/ansible/trash/test.yml:29
Using module file /usr/lib/python3/dist-packages/ansible_collections/community/postgresql/plugins/modules/postgresql_user.py
Pipelining is enabled.
<192.168.122.206> ESTABLISH SSH CONNECTION FOR USER: test
<192.168.122.206> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="test"' -o ConnectTimeout=10 -o 'ControlPath="/home/test/.ansible/cp/d384da5690"' 192.168.122.206 '/bin/sh -c '"'"'sudo -H -S -p "[sudo via ansible, key=zlotgdogafqupnwcibhpfdxbahjwrxrm] password:" -u postgres /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-zlotgdogafqupnwcibhpfdxbahjwrxrm ; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<192.168.122.206> (1, b'', b'Traceback (most recent call last):\n  File "<stdin>", line 107, in <module>\n  File "<stdin>", line 99, in _ansiballz_main\n  File "<stdin>", line 47, in invoke_module\n  File "/usr/lib/python3.10/runpy.py", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code\n    exec(code, run_globals)\n  File "/tmp/ansible_community.postgresql.postgresql_user_payload_qwcdgcif/ansible_community.postgresql.postgresql_user_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_user.py", line 1015, in <module>\n  File "/tmp/ansible_community.postgresql.postgresql_user_payload_qwcdgcif/ansible_community.postgresql.postgresql_user_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_user.py", line 935, in main\n  File "/tmp/ansible_community.postgresql.postgresql_user_payload_qwcdgcif/ansible_community.postgresql.postgresql_user_payload.zip/ansible_collections/community/postgresql/plugins/module_utils/postgres.py", line 187, in get_conn_params\nAttributeError: \'NoneType\' object has no attribute \'__version__\'\n')
<192.168.122.206> Failed to connect to the host via ssh: Traceback (most recent call last):
  File "<stdin>", line 107, in <module>
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 47, in invoke_module
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.postgresql.postgresql_user_payload_qwcdgcif/ansible_community.postgresql.postgresql_user_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_user.py", line 1015, in <module>
  File "/tmp/ansible_community.postgresql.postgresql_user_payload_qwcdgcif/ansible_community.postgresql.postgresql_user_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_user.py", line 935, in main
  File "/tmp/ansible_community.postgresql.postgresql_user_payload_qwcdgcif/ansible_community.postgresql.postgresql_user_payload.zip/ansible_collections/community/postgresql/plugins/module_utils/postgres.py", line 187, in get_conn_params
AttributeError: 'NoneType' object has no attribute '__version__'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 107, in <module>
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 47, in invoke_module
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.postgresql.postgresql_user_payload_qwcdgcif/ansible_community.postgresql.postgresql_user_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_user.py", line 1015, in <module>
  File "/tmp/ansible_community.postgresql.postgresql_user_payload_qwcdgcif/ansible_community.postgresql.postgresql_user_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_user.py", line 935, in main
  File "/tmp/ansible_community.postgresql.postgresql_user_payload_qwcdgcif/ansible_community.postgresql.postgresql_user_payload.zip/ansible_collections/community/postgresql/plugins/module_utils/postgres.py", line 187, in get_conn_params
AttributeError: 'NoneType' object has no attribute '__version__'
fatal: [192.168.122.206]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 107, in <module>\n  File \"<stdin>\", line 99, in _ansiballz_main\n  File \"<stdin>\", line 47, in invoke_module\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.postgresql.postgresql_user_payload_qwcdgcif/ansible_community.postgresql.postgresql_user_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_user.py\", line 1015, in <module>\n  File \"/tmp/ansible_community.postgresql.postgresql_user_payload_qwcdgcif/ansible_community.postgresql.postgresql_user_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_user.py\", line 935, in main\n  File \"/tmp/ansible_community.postgresql.postgresql_user_payload_qwcdgcif/ansible_community.postgresql.postgresql_user_payload.zip/ansible_collections/community/postgresql/plugins/module_utils/postgres.py\", line 187, in get_conn_params\nAttributeError: 'NoneType' object has no attribute '__version__'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ******************************************************************************************************************************************
192.168.122.206            : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

**Comment by hunleyd** [comment]
Thanks for the bug report! We'll look into it asap.

**Comment by Andersson007** [comment]
@codeInTheShell thanks for reporting the issue! Apologies for the later reply, was on PTO.

Looks like you use older version of the community.postgresql collection where was no check of required library in the code.
Could you please try to install the latest version of the collection with:
```
ansible-galaxy collection install community.postgresql
```
It will probably show that the `psycopg2` library needs to be installed (for your default Python interpreter) on your target machines.

Could you please try and tell us the result

Looking forward to you feedback

**Comment by Andersson007** [comment]
@codeInTheShell please take a look ^

**Comment by codeInTheShell** [comment]
```
test@test$ ansible-galaxy collection install community.postgresql -vvv
ansible-galaxy [core 2.12.4]
  config file = /home/test/ansible.cfg
  configured module search path = ['/home/test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/test/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-galaxy
  python version = 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0]
  jinja version = 3.0.3
  libyaml = True
Using /home/test/ansible.cfg as config file
Starting galaxy collection install process
Process install dependency map
ERROR! Unexpected Exception, this is probably a bug: CollectionDependencyProvider.find_matches() got an unexpected keyword argument 'identifier'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 128, in <module>
    exit_code = cli.run()
  File "/usr/lib/python3/dist-packages/ansible/cli/galaxy.py", line 569, in run
    return context.CLIARGS['func']()
  File "/usr/lib/python3/dist-packages/ansible/cli/galaxy.py", line 86, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ansible/cli/galaxy.py", line 1203, in execute_install
    self._execute_install_collection(
  File "/usr/lib/python3/dist-packages/ansible/cli/galaxy.py", line 1230, in _execute_install_collection
    install_collections(
  File "/usr/lib/python3/dist-packages/ansible/galaxy/collection/__init__.py", line 548, in install_collections
    dependency_map = _resolve_depenency_map(
  File "/usr/lib/python3/dist-packages/ansible/galaxy/collection/__init__.py", line 1364, in _resolve_depenency_map
    return collection_dep_resolver.resolve(
  File "/usr/lib/python3/dist-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3/dist-packages/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/lib/python3/dist-packages/resolvelib/resolvers.py", line 147, in _add_to_criteria
    matches = self._p.find_matches(
TypeError: CollectionDependencyProvider.find_matches() got an unexpected keyword argument 'identifier'
```
Same result with --upgrade.

**Comment by Andersson007** [comment]
@codeInTheShell thanks for the feedback, so now you get this error when trying to install the collection from galaxy, right?

**Comment by Andersson007** [comment]
1. another way to try could be updating the whole ansible package to the latest version
2. could you also please run `ansible-galaxy collection list | grep postgresql`?

**Comment by codeInTheShell** [comment]
```
ansible-galaxy collection list | grep postgresql
community.postgresql          1.7.1 
```

> 1. another way to try could be updating the whole ansible package to the latest version
You mean using ansible official ppa instead of the canonical one?

**Comment by Andersson007** [comment]
> You mean using ansible official ppa instead of the canonical one?

Yep

I've just checked the code. The [fix](https://github.com/ansible-collections/community.postgresql/blob/162fd14b96224e9fac4db148c14ad6fb48cc7320/plugins/modules/postgresql_user.py#L989) is in version 2 but hasn't been backported to version 1. I should do it.

**Comment by Andersson007** [comment]
@codeInTheShell hello, any feedback on the [comment](https://github.com/ansible-collections/community.postgresql/issues/386#issuecomment-1378682935)? if it works, the issue could be closed i think

**Comment by Andersson007** [comment]
closing this as no feedback, we can open it in future if needed.
thanks everyone
