### ISSUE TITLE
postgresql_ping fails when connecting to Azure postgresql (version has text after minor version)

### ISSUE THREAD

**Issue by joaocc** [ansible-collections/community.postgresql#40]
##### SUMMARY
postgresql_ping fails when connecting to Microsoft Azure postgresql with error `ValueError: invalid literal for int() with base 10: '6,'`
The query ```SELECT version()``` returns ```PostgreSQL 11.6, compiled by Visual C++ build 1800, 64-bit```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.general.postgresql_ping

##### ANSIBLE VERSION

```
ansible 2.10.4
  config file = /z/2now/kit-ar/19019-portal/19019-portal-ops/root/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /venv/ans/lib/python3.7/site-packages/ansible
  executable location = /venv/ans/bin/ansible
  python version = 3.7.9 (default, Dec 18 2020, 05:48:13) [GCC 9.3.0]
```

##### CONFIGURATION
```
```

##### EXPECTED RESULTS
Correct version being returned

##### ACTUAL RESULTS

Querying an Azure Postgresql server seems to break the version detection code, as it returns text after the version.
```
SELECT version()
PostgreSQL 11.6, compiled by Visual C++ build 1800, 64-bit
```

Ansible crash
```
Using module file /venv/ans/lib/python3.7/site-packages/ansible_collections/community/general/plugins/modules/postgresql_ping.py
Pipelining is enabled.
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '/venv/ans/bin/python3 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/local/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.general.postgresql_ping_payload_acr0tfma/ansible_community.general.postgresql_ping_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_ping.py", line 170, in <module>
  File "/tmp/ansible_community.general.postgresql_ping_payload_acr0tfma/ansible_community.general.postgresql_ping_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_ping.py", line 163, in main
  File "/tmp/ansible_community.general.postgresql_ping_payload_acr0tfma/ansible_community.general.postgresql_ping_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_ping.py", line 108, in do
  File "/tmp/ansible_community.general.postgresql_ping_payload_acr0tfma/ansible_community.general.postgresql_ping_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_ping.py", line 119, in get_pg_version
ValueError: invalid literal for int() with base 10: '6,'
fatal: [kar_platf__1dev]: FAILED! => changed=false 
  failed_when_result: true
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/local/lib/python3.7/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/local/lib/python3.7/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_community.general.postgresql_ping_payload_acr0tfma/ansible_community.general.postgresql_ping_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_ping.py", line 170, in <module>
      File "/tmp/ansible_community.general.postgresql_ping_payload_acr0tfma/ansible_community.general.postgresql_ping_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_ping.py", line 163, in main
      File "/tmp/ansible_community.general.postgresql_ping_payload_acr0tfma/ansible_community.general.postgresql_ping_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_ping.py", line 108, in do
      File "/tmp/ansible_community.general.postgresql_ping_payload_acr0tfma/ansible_community.general.postgresql_ping_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_ping.py", line 119, in get_pg_version
    ValueError: invalid literal for int() with base 10: '6,'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**Comment by Andersson007** [comment]
@joaocc thanks for reporting this! I created https://github.com/ansible-collections/community.postgresql/pull/43

**Comment by Andersson007** [comment]
FYI: `community.postgresql` collection has just been released.
The tarbal is available on [Galaxy](https://galaxy.ansible.com/community/postgresql).
How to install it, see the [official guide](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html).
The changes will also be included in the next Ansible release.
