### ISSUE TITLE
Case mismatch in postgresql_set causes MODULE FAILURE

### ISSUE THREAD

**Issue by davetapley** [ansible-collections/community.postgresql#41]
##### SUMMARY

Then trying to set [`timezone`](https://stackoverflow.com/a/32423177/21115) with `postgresql_set` I got a large error stack ending in `MODULE FAILURE` instead of it either:
* Just Working, or:
* Giving a clue to the workaround (use `name: TimeZone`).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`MODULE community.general.postgresql_set`

##### ANSIBLE VERSION

```paste below
ansible 2.10.1
  config file = None
  configured module search path = ['/home/dave/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dave/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION
None.

##### OS / ENVIRONMENT

Postgres installed on `Ubuntu 18.04.2 LTS` with:
```yaml
    - name: Add postgres apt key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add postgres apt repo
      apt_repository:
          repo: deb http://apt.postgresql.org/pub/repos/apt bionic-pgdg main
          state: present

    - name: Install postgres and Python prerequisites
      apt:
        name:
          - postgresql-10
          - python-setuptools
          - python-pip
```

##### STEPS TO REPRODUCE

```yaml
    - name: Set time zone to UTC
      become_user: postgres
      community.general.postgresql_set:
        name: "Timezone"
        value: "utc"
      register: timezone

```

##### EXPECTED RESULTS

Either it Just Worked, or gave me an error telling me what happened.
Even this would be useful, but I didn't see it in the output:
https://github.com/ansible-collections/community.postgresql/blob/ed91c875bd77f1d239ddc5bfbb3cf4d1e9d82aff/plugins/modules/postgresql_set.py#L201-L202

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/var/tmp/ansible-tmp-1610565309.636085-418-62394782136681/AnsiballZ_postgresql_set.py", line 102, in <module>
    _ansiballz_main()
  File "/var/tmp/ansible-tmp-1610565309.636085-418-62394782136681/AnsiballZ_postgresql_set.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/tmp/ansible-tmp-1610565309.636085-418-62394782136681/AnsiballZ_postgresql_set.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.postgresql_set', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_community.general.postgresql_set_payload_17xqrt/ansible_community.general.postgresql_set_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_set.py", line 447, in <module>
  File "/tmp/ansible_community.general.postgresql_set_payload_17xqrt/ansible_community.general.postgresql_set_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_set.py", line 350, in main
  File "/tmp/ansible_community.general.postgresql_set_payload_17xqrt/ansible_community.general.postgresql_set_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_set.py", line 202, in param_get
IndexError: list index out of range
fatal: [db_test]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 10.1.0.4 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/var/tmp/ansible-tmp-1610565309.636085-418-62394782136681/AnsiballZ_postgresql_set.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/var/tmp/ansible-tmp-1610565309.636085-418-62394782136681/AnsiballZ_postgresql_set.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/var/tmp/ansible-tmp-1610565309.636085-418-62394782136681/AnsiballZ_postgresql_set.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.postgresql_set', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_community.general.postgresql_set_payload_17xqrt/ansible_community.general.postgresql_set_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_set.py\", line 447, in <module>\r\n  File \"/tmp/ansible_community.general.postgresql_set_payload_17xqrt/ansible_community.general.postgresql_set_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_set.py\", line 350, in main\r\n  File \"/tmp/ansible_community.general.postgresql_set_payload_17xqrt/ansible_community.general.postgresql_set_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_set.py\", line 202, in param_get\r\nIndexError: list index out of range\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
```

**Comment by davetapley** [comment]
My workaround is to use `name: "TimeZone"`.
I found that via:
https://github.com/ansible-collections/community.postgresql/blob/ed91c875bd77f1d239ddc5bfbb3cf4d1e9d82aff/plugins/modules/postgresql_set.py#L192-L194

And then running `SELECT name, setting, unit, context, boot_val FROM pg_settings` on my DB I spotted:
```
 TimeZone                            | America/Phoenix                         |      | user              | GMT
```
---
This is especially silly since none? of the other settings use CamelCase:

```

**Comment by Andersson007** [comment]
@davetapley thanks for reporting this! I'm looking what we can do

**Comment by Andersson007** [comment]
https://github.com/ansible-collections/community.postgresql/pull/42

**Comment by Andersson007** [comment]
@davetapley please take a look https://github.com/ansible-collections/community.postgresql/pull/42

**Comment by Andersson007** [comment]
I'll merge the PR so the issue was automatically closed. Thanks!

**Comment by Andersson007** [comment]
FYI: `community.postgresql` collection has just been released.
The tarbal is available on [Galaxy](https://galaxy.ansible.com/community/postgresql).
How to install it, see the [official guide](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html).
The changes will also be included in the next Ansible release.
