### ISSUE TITLE
postgresql_set in check mode fails on non-numeric values containing `B`

### ISSUE THREAD

**Issue by k3rni** [ansible-collections/community.postgresql#48]
##### SUMMARY
When running in check mode, `postgresql_set` throws an exception if the value to set contained the letter `B`, or other binary units like `KB, MB`, but was **not** numeric otherwise.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_set

##### ANSIBLE VERSION
```
ansible 2.10.5
  config file = /home/k3rni/Source/ansible-bug-b/ansible.cfg
  configured module search path = ['/home/k3rni/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/k3rni/.asdf/installs/python/3.8.6/lib/python3.8/site-packages/ansible
  executable location = /home/k3rni/.asdf/installs/python/3.8.6/bin/ansible
  python version = 3.8.6 (default, Dec 17 2020, 13:42:12) [GCC 10.2.0]
```

##### CONFIGURATION
```paste below
DEFAULT_STDOUT_CALLBACK(/home/k3rni/Source/ansible-bug-b/ansible.cfg) = debug
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
Minimal playbook, assumes postgres is on localhost. Provide `login_host` etc. otherwise.
```yaml
- hosts: localhost
  tasks:
    - community.general.postgresql_set:
        name: maintenance_work_mem
        value: 100MB

    - community.general.postgresql_set:
        name: archive_command
        value: '/usr/bin/touch %f' # NOTE: contains lowercase B, and not a very useful archive_command to set
```

Run in check mode:
```shell
ansible-playbook -i example.yml -C
```

##### EXPECTED RESULTS
Command completes successfully, reporting if the parameters need changing.

##### ACTUAL RESULTS

```
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ****************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************
ok: [localhost]

TASK [community.general.postgresql_set] *****************************************************************************************************************************************
ok: [localhost]

TASK [community.general.postgresql_set] *****************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: invalid literal for int() with base 10: ''
fatal: [localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/home/k3rni/.ansible/tmp/ansible-tmp-1611934980.1523125-10330-89490691781095/AnsiballZ_postgresql_set.py", line 102, in <module>
    _ansiballz_main()
  File "/home/k3rni/.ansible/tmp/ansible-tmp-1611934980.1523125-10330-89490691781095/AnsiballZ_postgresql_set.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/k3rni/.ansible/tmp/ansible-tmp-1611934980.1523125-10330-89490691781095/AnsiballZ_postgresql_set.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.postgresql_set', init_globals=None, run_name='__main__', alter_sys=True)
  File "/home/k3rni/.asdf/installs/python/3.8.6/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/k3rni/.asdf/installs/python/3.8.6/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/k3rni/.asdf/installs/python/3.8.6/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.general.postgresql_set_payload_owlfxker/ansible_community.general.postgresql_set_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_set.py", line 447, in <module>
  File "/tmp/ansible_community.general.postgresql_set_payload_owlfxker/ansible_community.general.postgresql_set_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_set.py", line 376, in main
  File "/tmp/ansible_community.general.postgresql_set_payload_owlfxker/ansible_community.general.postgresql_set_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_set.py", line 255, in pretty_to_bytes
ValueError: invalid literal for int() with base 10: ''
```

The problem is, as indicated by the traceback, in [line 383](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_set.py#L383) of the postgres_set module. In check mode, it passes the value into `pretty_to_bytes` without checking if it's actually a number. That function, in turn, [finds the B](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_set.py#L261) in `/usr/bin`, and attempts to collect all digits, only to come up with none.

**Comment by Andersson007** [comment]
@k3rni  thanks reporting the issue!

CC @Dorn- @andytom @ilicmilan @kostiantyn-nemchenko @matburt @nerzhul @sebasmannem @tcraxs

if anybody wants to fix this, please, put your intention here ASAP not to work in parallel (I'll also do it if I decide). I'd be happy to review any related fixes. Thanks!

**Comment by Andersson007** [comment]
FYI: I'm fixing this

**Comment by Andersson007** [comment]
I created https://github.com/ansible-collections/community.postgresql/pull/52
ready_for_review
