### ISSUE TITLE
Superuser flag unnecessarily needed ?

### ISSUE THREAD

**Issue by andreagrax** [ansible-collections/community.postgresql#96]
##### SUMMARY
superuser is required to create a non-superuser one, tested against aws rds which does have a limited `postgres` user.

Connecting with `psql` and doing `user create` and also `alter user` works fine, but the second run of `postgfresql_user` fails with `psycopg2.errors.InsufficientPrivilege: must be superuser to alter superusers`
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_user
##### ANSIBLE VERSION

also tested with ansible 2.8.11
`psycopg2` is 2.8.6

```paste below
/ansible $ ansible --version
ansible 2.9.20
  config file = /ansible/ansible_with_vault.cfg
  configured module search path = ['/home/andrea/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.10 (default, Mar  2 2021, 09:06:08) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/ansible-testme/ansible_with_vault.cfg) = True
ANSIBLE_SSH_ARGS(/ansible-testme/ansible_with_vault.cfg) = -o UserKnownHostsFile=./ssh_known_hosts -o ForwardAgent=yes -o ConnectTimeout=30 -o ControlMaster=auto -o ControlPersist=180s -o ControlPath=.ansible_ssh/master-%r@%h:%p.socket
CACHE_PLUGIN(/ansible-testme/ansible_with_vault.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/ansible-testme/ansible_with_vault.cfg) = ./ansible-fact_caching
CACHE_PLUGIN_TIMEOUT(/ansible-testme/ansible_with_vault.cfg) = 86400
DEFAULT_CALLBACK_WHITELIST(/ansible-testme/ansible_with_vault.cfg) = ['profile_tasks']
DEFAULT_FORKS(/ansible-testme/ansible_with_vault.cfg) = 20
DEFAULT_GATHERING(/ansible-testme/ansible_with_vault.cfg) = smart
DEFAULT_HOST_LIST(/ansible-testme/ansible_with_vault.cfg) = ['/ansible-testme/NOTHING']
DEFAULT_LOG_PATH(/ansible-testme/ansible_with_vault.cfg) = /ansible-testme/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/ansible-testme/ansible_with_vault.cfg) = ['/ansible-testme/plugins/lookup']
DEFAULT_ROLES_PATH(/ansible-testme/ansible_with_vault.cfg) = ['/ansible-testme/roles']
DEFAULT_STDOUT_CALLBACK(/ansible-testme/ansible_with_vault.cfg) = debug
DEFAULT_STRATEGY(/ansible-testme/ansible_with_vault.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/ansible-testme/ansible_with_vault.cfg) = ['/usr/lib/python3.7/site-packages/ansible_mitogen/plugins/strategy']
DEFAULT_TIMEOUT(/ansible-testme/ansible_with_vault.cfg) = 30
DEFAULT_VAULT_IDENTITY_LIST(/ansible-testme/ansible_with_vault.cfg) = ['pre_ca@../ansible-testme-vault/pre_ca.txt', 'production@../ansible-testme-vault/production.txt', 'pre@../ansible-testme-vault/pre.txt', 'old@../ansible-testme-vault/old.txt']
DIFF_ALWAYS(/ansible-testme/ansible_with_vault.cfg) = True
DISPLAY_SKIPPED_HOSTS(env: ANSIBLE_DISPLAY_SKIPPED_HOSTS) = False
HOST_KEY_CHECKING(/ansible-testme/ansible_with_vault.cfg) = True
MAX_FILE_SIZE_FOR_DIFF(/ansible-testme/ansible_with_vault.cfg) = 104857600
PERSISTENT_COMMAND_TIMEOUT(/ansible-testme/ansible_with_vault.cfg) = 180
PERSISTENT_CONNECT_TIMEOUT(/ansible-testme/ansible_with_vault.cfg) = 180
```

##### OS / ENVIRONMENT

controller : ansible on docker (alpine) container. 
Target : AWS RDS postgres 

##### STEPS TO REPRODUCE

On a vanilla postgresql istance this code is idempotent.
If run against a AWS RDS postgres instance (where the postgres user miss the `supersuer` flag, see [this serverfault answer](https://serverfault.com/questions/661661/why-cant-i-create-a-superuser-in-aws-postgresql-instance) the first run is succesful, the second one throws this error : 

`psycopg2.errors.InsufficientPrivilege: must be superuser to alter superusers`

```yaml
    - name: create the user
      postgresql_user:
        login_host: "{{ postgres_login_host }}"
        login_user: "{{ postgres_login_user }}"
        login_password: "{{ postgres_login_password }}"
        name: "{{ pg_username }}"
        password: "{{ pg_password }}"
        role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE,NOINHERIT
        state: present
```

##### EXPECTED RESULTS

User is created succesfully, and task is not changed on subsequent runs

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: psycopg2.errors.InsufficientPrivilege: must be superuser to alter superusers
fatal: [my.host.net -> localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "master:/usr/lib/python3.7/site-packages/ansible_mitogen/runner.py", line 975, in _run
    self._run_code(code, mod)
  File "master:/usr/lib/python3.7/site-packages/ansible_mitogen/runner.py", line 939, in _run_code
    exec(code, vars(mod))
  File "master:/usr/lib/python3.7/site-packages/ansible/modules/database/postgresql/postgresql_user.py", line 871, in <module>
  File "master:/usr/lib/python3.7/site-packages/ansible/modules/database/postgresql/postgresql_user.py", line 825, in main
  File "master:/usr/lib/python3.7/site-packages/ansible/modules/database/postgresql/postgresql_user.py", line 433, in user_alter
  File "/usr/lib/python3.7/site-packages/psycopg2/extras.py", line 146, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.errors.InsufficientPrivilege: must be superuser to alter superusers
```

**Comment by Andersson007** [comment]
@andreagrax hi, thanks for reporting the issue!
If i understand correctly, the first run on RDS works well and all the subsequent fail, right?

Have you tried to use `no_password_changes: yes` in the task?
I'd be grateful for feedback.
Thanks!

**Comment by andreagrax** [comment]
@Andersson007 yes, you're correct.
first run is OK, subsequent ones fails.

I've tried with `no_password_changes: yes` and it  doesn't change the outcome

**Comment by Andersson007** [comment]
@andreagrax thanks for the feedback!
I guess it could mean that there's a place somewhere else in the code (in `user_alter`) which tries to update a user on RDS not having some information (similarly to the password case with Amazon mentioned).
If anyone wants to take a look, it would be great. Not sure if i can investigate this soon.

CC @tcraxs @andytom @kostiantyn-nemchenko @sebasmannem @ilicmilan @popov83

**Comment by Andersson007** [comment]
(if anyone from newcomers has ideas how to fix it, we have a quick start guide in https://github.com/ansible-collections/community.postgresql/blob/main/CONTRIBUTING.md)

**Comment by karthikprabakaran** [comment]
Is there a way to resolve this issue ?.

**Comment by jchancojr** [comment]
@andreagrax and @karthikprabakaran,

The issue here is in the `role_attr_flags` line. Specifically, the `NOSUPERUSER` attribute. Attempting to `ALTER` a user with `(NO)SUPERUSER` present, in RDS, will fail with the error you've encountered regardless of Ansible:
```
postgres=> CREATE USER foo NOSUPERUSER;
CREATE ROLE
postgres=> ALTER USER foo NOSUPERUSER;
ERROR:  must be superuser to alter superusers
postgres=> ALTER USER foo NOINHERIT;
ALTER ROLE
postgres=> ALTER USER foo INHERIT NOSUPERUSER;
ERROR:  must be superuser to alter superusers
postgres=>
```

Altering the playbook to the following works:

```
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: create the user
      postgresql_user:
        login_host: "host"
        login_user: "postgres"
        login_password: "secret"
        name: "luke"
        password: "jedi"
        role_attr_flags: NOCREATEDB,NOCREATEROLE,NOINHERIT
        state: present
```

You could also simply remove the `role_attr_flags` line entirely as these values are the defaults. 

I'll update the module documentation and investigate whether or not workaround this RDS bug.

**Comment by Andersson007** [comment]
The doc PR has been merged, thank you all!
